name: Node.js CI

on:
  push:
    branches:
      - main          # Trigger on push to main branch
  pull_request:
    branches:
      - main          # Trigger on PR targeting main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'   # Specify Node.js version to use

      - name: Install dependencies
        run: |
          yarn install       # or npm install

      - name: Run tests
        run: |
          yarn test          # or npm test
